language: cpp
# run on new infrastructure
sudo: false
cache: apt
# required packages to install
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - gperf
      - autoconf
      - automake
      - autotools-dev
      - libmpc-dev
      - libmpfr-dev
      - libgmp-dev
      - gawk
      - build-essential
      - bison
      - flex
      - texinfo
      - python-pexpect
      - libusb-1.0-0-dev
      - device-tree-compiler

env:
  global:
    - RISCV="/home/travis/riscv_install"
    - MAKEFLAGS="-j4"
    - PATH="/home/travis/riscv_install/bin:$PATH"
jobs:
  include:
    - stage: pre
      before_install:
        # make install destination
        - mkdir -p $RISCV
        # don't forget to clone riscv-tests/env
        - cd riscv-tests
        - git submodule update --init
        - cd ..
        # openocd also needs submodules
        - cd riscv-openocd
        - git submodule update --init
        - cd ..
        # actually use new gcc
        - export CXX=g++-4.8 CC=gcc-4.8
        - . build.common

      # pexpect ends up in /usr/lib/python2.7/dist-packages, which is not part of the
      # default python path.
      script:
        - build_project riscv-openocd --prefix=$RISCV --enable-remote-bitbang --enable-jtag_vpi --disable-werror
    - stage: a 
      script:
      - build_project riscv-isa-sim --prefix=$RISCV
    - stage: b
      script:
      - build_project riscv-gnu-toolchain --prefix=$RISCV --disable-gdb
    - stage: c
      script:
      - build_project fsf-binutils-gdb --prefix=$RISCV --target=riscv64-unknown-elf
    - stage: d
      script:
      - CC= CXX= build_project riscv-pk --prefix=$RISCV --host=riscv64-unknown-elf
    - stage: e
      script:
      - build_project riscv-tests --prefix=$RISCV/riscv64-unknown-elf
    - stage: f
      script:
      - PYTHONPATH=$PYTHONPATH:/usr/lib/python2.7/dist-packages make -C riscv-tests/build debug-check-fast
